
all:
	(cd lib;make)
	(cd dlx;make)
	(cd oa-64;make)

depend:
	(cd lib;make depend)
	(cd dlx;make depend)
	(cd oa-64;make depend)

clean:
	(cd lib;make clean)
	(cd dlx;make clean) 
	(cd oa-64;make clean) 
