#!/bin/sh 

if [ "X$HAWKROOT" = "X" ] ; then
     echo "HAWKROOT environment variable not set"
     exit
fi

if [ ! -d $HAWKROOT ] ; then
   echo "ERROR: Directory $HAWKROOT not found"
   exit 1
fi


. $HAWKROOT/bin/common

${MKDEPEND} -o hi -fglasgow-exts -i${HAWKLIB} $*
